misc: install git in final image
git is required for the terraform-aws-vpc module to be setup,
apparently.

```
2024/10/01 16:26:32 e2e.go:92: Failed to set up or retrieve cluster: could not launch cluster: create cluster failed: create hcp cluster vpc failed: failed to perform terraform init: error running terraform init: exit status 1

Error: Failed to download module

  on setup-hcp-vpc.tf line 53:
  53: module "vpc" {

Could not download module "vpc" (setup-hcp-vpc.tf:53) source code from
"git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=faa7ad9cd9a9ec98c4e2dfc1e5b370b4558cd23b":
error downloading
'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=faa7ad9cd9a9ec98c4e2dfc1e5b370b4558cd23b':
git must be available and on the PATH.
```

Signed-off-by: Brady Pratt <bpratt@redhat.com>