e2e: increase hibernation time for nightly clusters
10 minutes seems to be too short, the cluster was already not found by
the time cleanup was running

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1701907186206117888/artifacts/rosa-classic-sts/osde2e-cleanup/build-log.txt

```
2023/09/13 14:12:13 retryer.go:25: error during OCM attempt: couldn't retrieve cluster '267k8n40rj3rea58jf44virq0363kmlh': status is 404, identifier is '404', code is 'CLUSTERS-MGMT-404' and operation identifier is '34680996-a3d2-4ef5-acc6-511a693e3ee7': Cluster '267k8n40rj3rea58jf44virq0363kmlh' not found
```

This will be one cause on why things are getting left up since
hibernation will not delete the additional resources

Signed-off-by: Brady Pratt <bpratt@redhat.com>